### ISSUE TITLE
Flashblocks RPC call returns null

### ISSUE THREAD

**Issue by Curu24** [base/base#187]
Hello,

I'm running base-reth-node binary v0.1.16 (together with op-node 1.14.3) in a following systemd setup
```
ExecStart=/usr/local/bin/base-reth-node node \
  --chain base \
  --datadir /var/lib/base \
  --http \
  --http.api "eth,web3,net,txpool,admin" \
  --http.disable-compression \
  --ws \
  --ws.api "eth,web3,net,txpool,admin" \
  --ws.origins "*" \
  --authrpc.addr 127.0.0.1 \
  --authrpc.port 8551 \
  --authrpc.jwtsecret /var/lib/base/engine-auth-jwt \
  --peers-file /var/lib/base/trusted-nodes.json \
  --metrics 0.0.0.0:6060 \
  --rollup.sequencer-http https://mainnet-sequencer.base.org \
  --full \
  --log.stdout.format log-fmt \
  --log.stdout.filter info \
  --websocket-url wss://mainnet.flashblocks.base.org/ws \
```
For some time the node runs well and flashblocks rpc call gives response, but there are long periods where the flashblocks rpc call returns null. e.g.
```
curl -s localhost:8545 -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending",false],"id":1}'

{"jsonrpc":"2.0","id":1,"result":null}
```
each period is preceded by 2 errors appearing in the logs:
```
level=error target=base_reth_flashblocks_rpc::subscription message="error receiving message" error="WebSocket protocol error: Connection reset without closing handshake"
level=error target=base_reth_flashblocks_rpc::state message="Received non-sequential Flashblock for current block, zeroing Flashblocks until we receive a base Flashblock" curr_block=38004618 new_block=38004618
```
and then this error repeats every regular block
```
level=error target=base_reth_flashblocks_rpc::state message="could not process Flashblock" error="Failed to extract header for canonical block number 38004618. This is okay if your node is not fully synced to tip yet."
```

Eaxmple of the full log is here with first part around the time when flashblocks start malfunctioning and second part when they kick in again (the 2 parts separated by 3 blank lines) https://pastebin.com/FT9nng6E

**Comment by Parizval** [comment]
@Curu24, This issue is being worked upon in #178 Issue.

**Comment by Curu24** [comment]
> [@Curu24](https://github.com/Curu24), This issue is being worked upon in [#178](https://github.com/base/node-reth/issues/178) Issue.

great, thanks

**Comment by Parizval** [comment]
@Curu24, The Issue has been fixed and you could test out in the new release.

**Comment by Curu24** [comment]
@Parizval upgraded to base-reth-node v0.2.0 and op-node v1.16.1 and running the setup for 1.5 hours already, but still getting
```
curl -s localhost:8545 -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending",false],"id":1}'
{"jsonrpc":"2.0","id":1,"result":null}
```
and in the log I can still see
```
level=error target=base_reth_flashblocks_rpc::state message="could not process Flashblock" error="Failed to extract header for canonical block number 38124272. This is okay if your node is not fully synced to tip yet."
```
isn't it that the issue in this comment needs to be fixed for the flashblocks to work correctly?
https://github.com/base/node-reth/issues/178#issuecomment-3522264552

**Comment by danyalprout** [comment]
@Curu24 it isn't in formal release yet, you would have to use the build from main. We'll cut a release with this once we've finished the work for Jovian.

**Comment by Curu24** [comment]
@danyalprout oh ok, thanks for the info

**Comment by danyalprout** [comment]
This should be fixed in the latest release
